### PR TITLE
Co-locate tests with implementations.

### PR DESCRIPTION
**Pull request by mbrandonw**
This is something @justinswart and I experimented with in the [`LiveStream` framework](https://github.com/kickstarter/ios-oss/tree/master/LiveStream) in the main app and it worked out quite well. Basically, we just move all tests to be in the same directory as the implementation file. Less searching for tests and less maintaining of parallel directory structures.

Whatdyall think?

### CODE REVIEW

**Comment by mbrandonw** [comment]
btw, if y'all are into this idea i'll open PR's to do it for our dependencies and main app too

**Comment by mbrandonw** [comment]
oh and screenshot of what it looks like in practice:

screenshot 2017-03-22 11 47 00

**Comment by justinswart** [comment]
Yip this makes sense! We'd of course just need to align our swiftlint rules too.

Were there any other 'target-specific' stuff we were doing for tests? I recall when we did this for LiveStream we identified one or two hurdles (like the swiftlint rules) that prevented us from just doing it at the same time.

**Comment by mbrandonw** [comment]
> Were there any other 'target-specific' stuff we were doing for tests? I recall when we did this for LiveStream we identified one or two hurdles (like the swiftlint rules) that prevented us from just doing it at the same time.

yup swiftlint is the main hurdle (and I think only?). swiftlint doesnt factor into prelude, reactive extensions or ksapi cause they are simple enough. in the main app we'll get rid of the test specific `.swiftlint.yml` and instead go with one global config. i think that's better in the end, but means no more force unwrapping in tests. @stephencelis and i have a way to mitigate that so that it isn't annoying to deal with (it's p nice actually!). more details to come...

**Pull request merged**
